platform :ios, '12.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'CoreMobile' do

  # React Native Maps dependencies (Must be before use_native_modules)
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  use_native_modules!
end

target 'CoreMobile-tvOS' do
  # Pods for CoreMobile-tvOS

  target 'CoreMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
